import { assetsTypes } from '../utils/assetTypes'

export default {
    familyChartVisiblity: 'hidden',
    search_string: null,
    search_rf_id: [],
    breadcrumbs: '',
    categoryName: 'Maintainence > Pay Maintainence Fee',
    selectedCategory: 'pay_maintainence_fee',
    layout_id: 0,
    assetTypes: { list: [], row_select: [], selected: [], selectAll: false, loading: false, loading_companies: true },
    assetTypeCompanies: { list: [], row_select: [], total_records: 0, selected: [], selectAll: false, loading: false },
    assetTypeAssignments: { list: [], total_records: 0, selected: [], selectAll: false, loading: false, children: { ist: [], total_records: 0, loading: false, selected:[] } },
    assetTypeAssignmentAssets: { list: [], total_records: 0, selected: [], selectAll: false, loading: false},
    maintainence_fee_file_name: 'MaintainenceFee',
    document_transaction: [],
    move_assets: [],
    channel_id: '',
    slack_auth_token: null,
    google_auth_token: null,
    google_profile: null,    
    slack_profile_data: null,
    slack_channel_list: [],
    slack_messages: [],
    slack_users: [], 
    drive_files: { files: [], nextPageToken: '' },
    template_drive_files: [], 
    new_drive_template_file: null,
    template_document_url: 'about:blank',
    driveButtonActive: false,
    maintainenceAssetsLoadingMore: false,
    maintainenceAssetsList: {list: [], total_records: 0}, 
    mainCompaniesList: { list: [], total_records: 0, row_select: [], selected: [], selectedWithName: [], selectAll: false },
    mainCompaniesSelected: [], 
    mainCompaniesLoadingMore: false,
    selectedMaintainencePatents: [],
    companiesList: [], 
    companyListLoading: false, 
    assetsCustomersLoading: false,
    assetsCustomersLoadingMore: false,
    assetsTransactionsLoading: false,
    assetsPatentsLoading: false,
    gridWidthClassNumber: 12, 
    activeMenuButton: -1,
    assets: assetsTypes.reduce((result, assetType) => {
      result[assetType] = {} 
      return result 
    }, {}),
    reviewTransactionView: { assetType: 0, customerId: 0, companyId: 0 },
    selectedCompaniesList: [],
    selectedAssetsTypes: [ 'acquisitions' ],
    selectedAssetsCustomers: [],
    selectedAssetsTransactions: [],
    selectedChildAssetsTransactions: [],
    selectedAssetsPatents: [], 
    childSelectedAssetsPatents: [],
    assetTypeChildCompanies: { row_select: [], selected: [], selectAll: false },
    transaction_life_span: [],
    loadingAssetIllustration: false,
    loadingAssetUSPTO: false,
    assetIllustration: null,
    assetUSPTO: {},
    selectedCommentsEntity: null,    
    assetsRecordsDataCount: 0,
    isLoadingAssetsRecordsDataCount: null,
    assetsCompActivitiesDataCount: 0,
    isLoadingCompActivitiesDataCount: null,
    isLoadingAssetsErrorsDataCount: null,
    assetsErrorsDataCount: 0
}