import { assetsTypes } from '../utils/assetTypes'
import { BlurLinear } from '@mui/icons-material'

export default {
    auth_token: null,
    familyChartVisiblity: 'hidden',
    switch_button_assets: 0,
    search_string: null,
    search_rf_id: [],
    breadcrumbs: '',
    dashboardPanelActiveButtonId: -1,
    categoryName: 'Legal > Due Diligence',
    selectedCategory: 'due_dilligence',
    layout_id: 0,
    clipboard_assets: [],
    foreignAssets: { selected: [], selectNames: [] },
    assetTypes: { list: [], row_select: [], selected: [], selectAll: false, loading: false, loading_companies: true },
    assetTypeCompanies: { list: [], row_select: [], total_records: 0, selected: [], selectAll: false, loading: false , name: ''},
    assetTypeInventors: { list: [], total_records: 0, loading: false},
    assetTypeAssignments: { list: [], total_records: 0, selected: [], selectAll: false, loading: false, children: { list: [], total_records: 0, loading: false, selected:[] } },
    assetTypeAddress: { list: [], row_select: [], all_groups: [], total_records: 0, selected: [], selectAll: false, loading: false },
    assetTypeNames: { list: [], row_select: [], all_groups: [], total_records: 0, selected: [], selectAll: false, loading: false },
    assetTypeAssignmentAssets: { list: [], total_records: 0, selected: [], selectAll: false, loading: false},
    assetTableScrollPosition: 0,
    asset_details:{asset: null, family: 0, claims: 0, figures: 0, fees: 0, citations: 0, ptab: 0, litigation: 0, status: 0},
    ptabAssets: [],
    addressQueuesDisplay: false,
    addressQueuesLoading: false,
    addressQueues: [],
    fixedTransactionAddress:[],
    link_assets_sheet_display: false,
    link_assets_sheet_loading: false,
    link_assets_sheet_list: [],
    link_assets_selected: [],  
    link_assets_sheet_type:{type: null, asset: null},
    nameQueuesDisplay: false,
    nameQueuesLoading: false, 
    nameQueues: [],
    fixedTransactionName:[],
    maintainence_fee_file_name: 'MaintainenceFee',
    document_transaction: [],
    move_assets: [], 
    channel_id: '',
    slack_auth_token: null, 
    google_auth_token: null,
    google_profile: null,    
    slack_profile_data: null,
    slack_channel_list: [],
    slack_channel_list_loading: false,
    slack_messages: [],
    slack_users: [], 
    drive_files: { files: [], nextPageToken: '' },
    template_drive_files: [], 
    new_drive_template_file: null,
    template_document_url: 'about:blank',
    display_sales_assets: false,
    display_clipboard: false, 
    driveButtonActive: false,
    maintainenceAssetsEventsLoadingMore: false,
    maintainenceAssetsEventsList: {list: []}, 
    maintainenceAssetsLoadingMore: false,
    maintainenceAssetsList: {list: [], total_records: 0}, 
    mainCompaniesList: { list: [], total_records: 0, row_select: [], selected: [], selectedWithName: [], selectedGroups: [], selectAll: false, childID: 0, child_list: [] },
    mainCompaniesLoadingMore: false,
    selectedMaintainencePatents: [],
    companiesList: [], 
    companyListLoading: false, 
    assetsCustomersLoading: false,
    assetsCustomersLoadingMore: false,
    assetsTransactionsLoading: false,
    assetsPatentsLoading: false,
    gridWidthClassNumber: 12, 
    activeMenuButton: -1,
    selectedLawFirm: 0,
    assets: assetsTypes.reduce((result, assetType) => {
      result[assetType] = {} 
      return result 
    }, {}),
    reviewTransactionView: { assetType: 0, customerId: 0, companyId: 0 },
    selectedCompaniesList: [],
    selectedAssetsTypes: [ 'acquisitions' ],
    selectedAssetsCustomers: [],
    selectedAssetsTransactions: [],
    selectedChildAssetsTransactions: [],
    selectedAssetsPatents: [], 
    childSelectedAssetsPatents: [],
    assetTypeChildCompanies: { row_select: [], selected: [], selectAll: false },
    transaction_life_span: [],
    loadingAssetIllustration: false,
    loadingAssetUSPTO: false,
    assetIllustration: null,
    assetIllustrationData: null,
    assetUSPTO: {},
    selectedCommentsEntity: null,    
    assetsRecordsDataCount: 0,
    isLoadingAssetsRecordsDataCount: null,
    assetsCompActivitiesDataCount: 0,
    isLoadingCompActivitiesDataCount: null,
    isLoadingAssetsErrorsDataCount: null,
    assetsErrorsDataCount: 0
}