export default {
  isDarkTheme: true,
  maintainenceFrameMode: false,
  driveTemplateFrameMode: false,
  driveTemplateMode: false,
  usptoMode: false,
  showThirdParties: true,
  lifeSpanMode: false,
  familyMode: false,
  familyItemMode: false,
  familyActiveTab: 0,
  timeline: {
    selectedItem: null,
    selectedAsset: null,
  },
  assetButton: false,
  patentScreen: false,
  transactionButton: false,
  timelineScreen: false,
  dashboardScreen: process.env.REACT_APP_ENVIROMENT_MODE === 'STANDARD' || process.env.REACT_APP_ENVIROMENT_MODE === 'SAMPLE' ? false : true,
  dashboardPanel: true,
  controlModal: process.env.REACT_APP_ENVIROMENT_MODE === 'STANDARD' || process.env.REACT_APP_ENVIROMENT_MODE === 'SAMPLE-1' ? false : false, 
  driveButtonActive: false,
  loadingDashboardData: false,
  viewDashboard: {
    line: false,
    gauge: process.env.REACT_APP_ENVIROMENT_MODE === 'DASHBOARD' ? true : false,
    jurisdictions: false,
    invention: false,
    sankey: false,
    kpi: process.env.REACT_APP_ENVIROMENT_MODE === 'DASHBOARD' ? false : true,
    timeline: false
  },
  viewInitial: false,
  familyLegalItemMode: false,
  sankeyFilterActive: false,
  viewIntro: false, 
  firstBarSize: 250,
  companyColWidth: 170
}