import routeList from '../routeList'

export const controlList = [
    {
        type: 'category',
        name: 'Maintenance',
        class: 'hex-0',
        mainHeadingClass: 'maintain',
    },
    {
        type: 'menu',
        mainHeading: 'Chain-of-Title',			
        subHeading: 'Get a list of all patents with broken chain of title, investigate with your team, and automatically correct the records.',
        svg: ``,
        image: 'https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/restore_ownership.png',
        class: 'hex-1',
        breadCrumbs: 'Chain-of-Title',
        category: 'restore_ownership',
        layout_id: 1,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.restore_ownership
    },
    {
        type: 'menu',
        mainHeading: 'Maintenance Fee Due',
        subHeading: 'Get a list of all patents due for payment, discuss with your team whether to maintain each one, and pay directly with the Patent Office.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/pay_maintainence_fees.png`,
        class: 'hex-3',
        breadCrumbs: 'Maintenance Fee Due',
        category: 'pay_maintainence_fee',
        layout_id: 3,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.pay_maintainence_fee
    },    
    {
        type: 'menu',
        mainHeading: 'Encumbrances',
        subHeading: 'Get a list of patents that are encumbared with third party rights that are likely removable.',
        svg: '',
        image: 'https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/clean_encumbrances.png',
        class: 'hex-2',
        breadCrumbs: 'Encumbrances',
        category: 'clear_encumbrances',
        layout_id: 2,
        showSvg: false,
        mainHeadingClass: 'maintain', 
        redirect: routeList.default
    },
    {
        type: 'menu',
        mainHeading: 'Correct Names',
        subHeading: 'Get a list of patents and assignments filed with incorrect address and correct them automatically.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/correct_address.png`,
        class: 'hex-4',
        breadCrumbs: 'Maintenance > Correct Names',
        category: 'correct_names',
        layout_id: 4,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.correct_details
    }, 
    {
        type: 'menu',
        mainHeading: 'Names',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/correct_address.png`,
        class: 'hex-9',
        breadCrumbs: 'Names',
        category: 'incorrect_names',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.default
    },    
    {
        type: 'menu',
        mainHeading: 'To Collateralize',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/correct_address.png`,
        class: 'hex-9',
        breadCrumbs: 'To Collateralize',
        category: 'incorrect_address',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.default
    },  
    {
        type: 'menu',
        mainHeading: 'Maintainance',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/correct_address.png`,
        class: 'hex-9',
        breadCrumbs: 'Maintainance',
        category: 'late_maintainance',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.patent_assets
    },
    {
        type: 'menu',
        mainHeading: 'Corrections',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/correct_address.png`,
        class: 'hex-9',
        breadCrumbs: 'Corrections',
        category: 'incorrect_recording',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.default
    },
    {
        type: 'menu',
        mainHeading: 'Recordings',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/correct_address.png`,
        class: 'hex-9',
        breadCrumbs: 'Recordings',
        category: 'late_recording',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'maintain',
        redirect: routeList.default
    },
    {
        type: 'category',
        name: 'Ownership',
        class: 'hex-5',
        mainHeadingClass: 'acquisition',
    },
    {
        type: 'menu',
        mainHeading: 'Invent',
        subHeading: 'Assign your employees\' inventions to the company.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Ownership > Invent',
        category: 'invent',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    }, 
    {
        type: 'menu',
        mainHeading: 'Acquire Patents',
        subHeading: 'Import a list of patents, review them, exchange your view with peers, and draft a PPA.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/acquire_patents.png`,
        class: 'hex-7',
        breadCrumbs: 'Ownership > Acquire Patents',
        category: 'acquire_patents',
        layout_id: 6,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.maintainence
    }, 
    {
        type: 'menu',
        mainHeading: 'Sell Patents',
        subHeading: 'Select patents from your portfolio, discuss them with your peers, and send them out to a broker/buyer, together with a comprehensive report.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/sell.png`,
        class: 'hex-8',
        breadCrumbs: 'Ownership > Sell Patents',
        category: 'sell_payments',
        layout_id: 7,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.maintainence
    },
    {
        type: 'menu',
        mainHeading: 'Insights',
        subHeading: 'Get a unique view of your assets. Explore your portfolio via collection of charts and KPI.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/insights.png`,
        class: 'hex-9',
        breadCrumbs: 'Ownership > Insights',
        category: 'insights',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.maintainence
    },    
    {
        type: 'menu',
        mainHeading: 'Names',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/insights.png`,
        class: 'hex-9',
        breadCrumbs: 'Names',
        category: 'incorrect_names',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.default
    },
    {
        type: 'category',
        name: 'Licensing',
        class: 'hex-10',
        mainHeadingClass: 'progress',
    },                
    {
        type: 'menu',
        mainHeading: 'License Out',
        subHeading: 'Select patents from your portfolio, discuss them with your peers, and send them out to a broker/licensees, together with a comprehensive report.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/licenseout.png`,
        class: 'hex-11',
        breadCrumbs: 'Licensing > License Out',
        category: 'licenseout',
        layout_id: 8,
        showSvg: false,
        mainHeadingClass: 'progress',
        redirect: routeList.maintainence
    },
    {
        type: 'menu',
        mainHeading: 'License In',
        subHeading: 'Import a list of patents, review them, exchange your view with peers, and draft your Patent License Agreement.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/licensein.png`,
        class: 'hex-12',
        breadCrumbs: 'Licensing > License In',
        category: 'licensein',
        layout_id: 9,
        showSvg: false,
        mainHeadingClass: 'progress',
        redirect: routeList.maintainence
    },
    {
        type: 'menu',
        mainHeading: 'Income/Expense',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/income_expense.png`,
        class: 'hex-13',
        breadCrumbs: 'Licensing > Income/Expense',
        category: 'income_expense',
        layout_id: 10,
        showSvg: false,
        mainHeadingClass: 'progress',
        redirect: routeList.maintainence
    },
    {
        type: 'menu',
        mainHeading: 'Survival Reports',
        subHeading: 'Produce reports showing the remaining life of patent portfolios you license out and license in.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/survival.png`,
        class: 'hex-14',
        breadCrumbs: 'Licensing > Survival Reports',
        category: 'reports',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'progress',
        redirect: routeList.maintainence
    },
    {
        type: 'category',
        name: 'Financing',
        class: 'hex-15',
        mainHeadingClass: 'bank',
    },                
    {
        type: 'menu',
        mainHeading: 'Secure a Loan',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/secure.png`,
        class: 'hex-16',
        breadCrumbs: 'Financing > Secure a Loan',
        /*category: 'secure_a_loan',*/
        category: 'correct_address',
        layout_id: 12,
        showSvg: false,
        mainHeadingClass: 'bank',
        redirect: routeList.correct_address
    },
    {
        type: 'menu',
        mainHeading: 'Reduce Interest Rate',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/reduce_interest_rate.png`,
        class: 'hex-17',
        breadCrumbs: 'Financing > Reduce Interest Rate',
        category: 'reduce_interest_rate',
        layout_id: 13,
        showSvg: false,
        mainHeadingClass: 'bank',
        redirect: routeList.maintainence
    },
    {
        type: 'menu',
        mainHeading: 'Release Collateral',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/release_collateral.png`,
        class: 'hex-18',
        breadCrumbs: 'Financing > Release Collateral',
        category: 'release_collateral',
        layout_id: 14,
        showSvg: false,
        mainHeadingClass: 'bank',
        redirect: routeList.maintainence
    },
    {
        type: 'menu',
        mainHeading: 'Market Review',
        subHeading: 'Expose yourself and learn so much from all the  assignment activities out there.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/market_review.png`,
        class: 'hex-19',
        breadCrumbs: 'Financing > Market Review',
        category: 'market_review',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'bank',
        redirect: routeList.maintainence
    },
    {
        type: 'category',
        name: 'Due Diligence',
        class: 'hex-20',
        mainHeadingClass: 'correct',
    },                
    {
        type: 'menu',
        mainHeading: 'Legal Ownership',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/due_dilligence.png`,
        class: 'hex-21',
        breadCrumbs: 'Due Diligence > Legal Ownership',
        category: 'due_dilligence',
        layout_id: 15,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'Locate Lost Assets',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/due_dilligence.png`,
        class: 'hex-21',
        breadCrumbs: 'Locate Lost Assets',
        category: 'locate_lost_assets',
        layout_id: 20,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'To Divest',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/due_dilligence.png`,
        class: 'hex-21',
        breadCrumbs: 'To Divest',
        category: 'unnecessary_patents',
        layout_id: 21,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'To Record',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/due_dilligence.png`,
        class: 'hex-21',
        breadCrumbs: 'To Record',
        category: 'missed_monetization',
        layout_id: 22,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'Deflated Collateral',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/due_dilligence.png`,
        class: 'hex-21',
        breadCrumbs: 'Deflated Collateral',
        category: 'deflated_collaterals',
        layout_id: 26,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'To Monetize',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/due_dilligence.png`,
        class: 'hex-21',
        breadCrumbs: 'To Monetize',
        category: 'to_be_monitized',
        layout_id: 17,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.locate_lost_assets
    },
    {
        type: 'menu',
        mainHeading: 'Technical Scope',
        subHeading: 'Get an immediate list of your patents involved in litigation.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/litigation.png`,
        class: 'hex-22',
        breadCrumbs: 'Legal > Technical Scope',
        category: 'technical_scope',
        layout_id: 16,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'Prosecution Process',
        subHeading: 'Get an immediate list of your patents involved in PTAB procedures.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/ptab.png`,
        class: 'hex-23',
        breadCrumbs: 'Legal > Prosecution Process',
        category: 'prosecution_process',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'menu',
        mainHeading: 'Litigation / PAIR',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/pair.png`,			
        class: 'hex-24',
        breadCrumbs: 'Legal > Litigation / PAIR',
        category: 'pair',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'correct',
        redirect: routeList.duedilligence
    },
    {
        type: 'category',
        name: 'Perfomance',
        class: 'hex-25',
        mainHeadingClass: 'read', 
    },                
    {
        type: 'menu',
        mainHeading: 'Lawyers',
        subHeading: 'An objective view of your lawyers\' performance, as well as that of other law firms.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/lawyers.png`,
        class: 'hex-26',
        breadCrumbs: 'Insights > Lawyers',
        category: 'lawyers',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'read',
        redirect: routeList.insights
    },
    {
        type: 'menu',
        mainHeading: 'Bankers',
        subHeading: 'An objective view of your bankers\' performance, as well as that of other banks.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/bankers.png`,
        breadCrumbs: 'Insights > Bankers',
        category: 'bankers',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'read',
        redirect: routeList.insights
    },
    {
        type: 'menu',
        mainHeading: 'Competitors',
        subHeading: 'Lean about your competitors activities.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/competitors.png`,
        class: 'hex-28',
        breadCrumbs: 'Insights > Competitors',
        category: 'competitors',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'read',
        redirect: routeList.insights
    },
    {
        type: 'menu',
        mainHeading: 'Inventors',
        subHeading: 'Analyse your inventor\'s activities.',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/inventors.png`,
        class: 'hex-29',
        breadCrumbs: 'Insights > Inventors',
        category: 'inventors',
        layout_id: 0,
        showSvg: false,
        mainHeadingClass: 'read',
        redirect: routeList.insights
    },
    {
        type: 'category',
        name: 'KPI',
        class: 'hex-5',
        mainHeadingClass: 'acquisition',
    },
    {
        type: 'menu',
        mainHeading: 'Owned',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Owned',
        category: 'assigned',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    }, 
    {
        type: 'menu',
        mainHeading: 'Invented',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Invented',
        category: 'filled',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Acquired',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Acquired',
        category: 'acquired',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Divested',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Divested',
        category: 'divested',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Collaterlized',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Collaterlized',
        category: 'collaterlized',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Abandoned',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Abandoned',
        category: 'abandoned',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Challenged (PTAB)',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Challenged (PTAB)',
        category: 'ptab',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Maintenance Fee Due',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Maintenance Budget',
        category: 'maintenance_budget',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Non-U.S. Members',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Non-U.S. Members',
        category: 'top_non_us_members',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Proliferate Inventors',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Proliferate Inventors',
        category: 'proliferate_inventors',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Law Firms',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Law Firms',
        category: 'top_law_firms',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Lenders',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Lenders',
        category: 'top_lenders',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'Uncollateralized',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Uncollateralized',
        category: 'uncollateralized',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'acquisition_transactions',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Acquisitions',
        category: 'acquisition_transactions',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'acquisition',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'divestitures_transactions',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Divestitures',
        category: 'divestitures_transactions',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'divestitures',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'licensing_transactions',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Licensing',
        category: 'licensing_transactions',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'licensing',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'collateralization_transactions',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Collateralization',
        category: 'collateralization_transactions',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'collateralization',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'inventing_transactions',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Inventing',
        category: 'inventing_transactions',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'inventing',
        redirect: routeList.invent
    },
    {
        type: 'menu',
        mainHeading: 'litigation_transactions',
        subHeading: '',
        svg: '',
        image: `https://s3-us-west-1.amazonaws.com/static.patentrack.com/icons/menu/invent.png`,
        class: 'hex-6',
        breadCrumbs: 'Litigation',
        category: 'litigation_transactions',
        layout_id: 5,
        showSvg: false,
        mainHeadingClass: 'litigation',
        redirect: routeList.invent
    },
]

export const menuControlList = [
    {
        name: 'Maintenance',
        children: [
            {
                mainHeading: 'Maintain\nPatents',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'maintain',
                redirect: routeList.review
            },
            {
                mainHeading: 'Restore\nOwnership',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'maintain',
                redirect: routeList.correct
            },       
            {
                mainHeading: 'Correct\nAddress',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'correct',
                redirect: routeList.correct
            },
            {
                mainHeading: 'Check\nProgress',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'progress',
                redirect: routeList.progress
            }
        ]
    }, 
    {
        name: 'Ownership',
        children: [
            {
                mainHeading: 'Inventors\nAssignment',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'acquisition',
                redirect: routeList.record
            },
            {
                mainHeading: 'Sell\nPatents',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'acquisition',
                redirect: routeList.review
            },
            {
                mainHeading: 'Buy\nPatents',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'acquisition',
                redirect: routeList.review
            },
            {
                mainHeading: 'Check\nProgress',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'progress',
                redirect: routeList.progress
            }
        ]
    },
    {
        name: 'Licensing',
        children: [
            {
                mainHeading: 'License\nIn',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'acquisition',
                redirect: routeList.review
            },        
            {
                mainHeading: 'License\nOut',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'acquisition',
                redirect: routeList.review
            },
            {
                mainHeading: 'Reports',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'correct',
                redirect: routeList.correct
            },
            {
                mainHeading: 'Check\nProgress',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'progress',
                redirect: routeList.progress
            }
        ]
    },
    {
        name: 'Financing',
        children: [
            {
                mainHeading: 'Secure a\nLoan',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'bank',
                redirect: routeList.review
            },
            {
                mainHeading: 'Reduce\nInterest Rate',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'bank',
                redirect: routeList.review
            },
            {
                mainHeading: 'Release\nCollateral',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'bank',
                redirect: routeList.review
            },
            {
                mainHeading: 'Check\nProgress',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'progress',
                redirect: routeList.progress
            }
        ]
    },
    {
        name: 'Due Diligence',
        children: [
            {
                mainHeading: 'Manage\nCounsel',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'correct',
                redirect: routeList.correct
            },
            {
                mainHeading: 'Reports',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'correct',
                redirect: routeList.correct
            },
            {
                mainHeading: 'Manage\nCounsel',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'correct',
                redirect: routeList.correct
            },
            {
                mainHeading: 'Manage\nBanks',
                subHeading: 'Identiy the patent which are due for payment of maintainance fee payment and pay afor all at once.',
                mainHeadingClass: 'progress',
                redirect: routeList.progress
            }
        ]
    }
]