export default {
  // Roots
  insights: '/insight',
  resources: '/resources', 
  dashboard_kpi: '/dashboard/',
  dashboard_attention: '/dashboard/attention',
  dashboard_activity: '/dashboard/activity',
  dashboard_share: '/dashboard/:code',
  restore_ownership: '/mainenance/restore_ownership',
  clear_encumbrances: '/mainenance/clear_encumbrances',
  pay_maintainence_fee: '/mainenance/pay_maintainence_fee',
  pay_maintainence_fee_share: '/mainenance/pay_maintainence_fee/:code',
  correct_details: '/mainenance/correct_names',
  correct_address: '/mainenance/correct_address',
  review_foreign_assets: '/review_external_assets',  
  locate_lost_assets: '/locate_lost_assets',
  patent_assets: '/patent_assets',
  patent_assets_layouts: '/patent_assets/:layout',
  patent_assets_layouts_share: '/patent_assets/:layout/:code',
  assignments: '/assignments',
  assignments_layouts: '/assignments/:layout',
  assignments_layouts_share: '/assignments/:layout/:code',
  invent: '/ownership/invent',
  duedilligence: '/due' ,
  search: '/search',
  reports: '/reports',
  global: '/global',
  default: '/',
  standard_default: '/:code',
  google_login: '/google_login' 
} 